// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PdrAutomate.WebUI.DataAccess.Concrete.EntityFramework;

namespace PdrAutomate.WebUI.Migrations
{
    [DbContext(typeof(PdrAutomateContext))]
    [Migration("20200227180800_NewDatabase")]
    partial class NewDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassCapacity");

                    b.Property<string>("ClassName");

                    b.HasKey("ClassId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.ClassPresentationsession", b =>
                {
                    b.Property<int>("ClassId");

                    b.Property<int>("PresentationsessionId");

                    b.Property<int>("CurrentCapacity");

                    b.HasKey("ClassId", "PresentationsessionId");

                    b.HasIndex("PresentationsessionId");

                    b.ToTable("ClassPresentationsessions");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.Presentation", b =>
                {
                    b.Property<int>("PresentationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PresentationName");

                    b.HasKey("PresentationId");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.PresentationSession", b =>
                {
                    b.Property<int>("PresentationSessionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PresentationID");

                    b.Property<int>("SessionId");

                    b.HasKey("PresentationSessionId");

                    b.HasIndex("PresentationID");

                    b.HasIndex("SessionId");

                    b.ToTable("PresentationSessions");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.Sessions", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndTime");

                    b.Property<int?>("PresentationId");

                    b.Property<DateTime>("StartTime");

                    b.HasKey("SessionId");

                    b.HasIndex("PresentationId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassId");

                    b.Property<string>("Password");

                    b.Property<string>("StudentName");

                    b.Property<string>("StudentSchoolId");

                    b.Property<string>("StudentSurname");

                    b.HasKey("StudentId");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.StudentPresentationsession", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("PresentationSessionId");

                    b.HasKey("StudentId", "PresentationSessionId");

                    b.HasIndex("PresentationSessionId");

                    b.ToTable("StudentPresentationsessions");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.ClassPresentationsession", b =>
                {
                    b.HasOne("PdrAutomate.WebUI.Entity.Class", "Class")
                        .WithMany("ClassPresentationsessions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PdrAutomate.WebUI.Entity.PresentationSession", "PresentationSession")
                        .WithMany("ClassPresentationsessions")
                        .HasForeignKey("PresentationsessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.PresentationSession", b =>
                {
                    b.HasOne("PdrAutomate.WebUI.Entity.Presentation", "Presentation")
                        .WithMany()
                        .HasForeignKey("PresentationID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PdrAutomate.WebUI.Entity.Sessions", "Sessions")
                        .WithMany("Presentations")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.Sessions", b =>
                {
                    b.HasOne("PdrAutomate.WebUI.Entity.Presentation")
                        .WithMany("Sessions")
                        .HasForeignKey("PresentationId");
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.Student", b =>
                {
                    b.HasOne("PdrAutomate.WebUI.Entity.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PdrAutomate.WebUI.Entity.StudentPresentationsession", b =>
                {
                    b.HasOne("PdrAutomate.WebUI.Entity.PresentationSession", "PresentationSession")
                        .WithMany("StudentPresentationsessions")
                        .HasForeignKey("PresentationSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PdrAutomate.WebUI.Entity.Student", "Student")
                        .WithMany("StudentPresentationsessions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
